@echo off
echo 开始启动网易云音乐代理程序...
cd /d D:\software\Unlock-netease-cloud-music-master\Unlock-netease-cloud-music-master
start "" cmd /k call netease.bat
echo 启动网易云音乐代理程序成功...
echo 开始启动网易云音乐...
cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs
start 网易云音乐.lnk
echo 启动网易云音乐成功...